version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: ghosttrack_db
    environment:
      POSTGRES_USER: ghosttrack
      POSTGRES_PASSWORD: ghosttrack_dev_password
      POSTGRES_DB: ghosttrack
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: ghosttrack_redis
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    container_name: ghosttrack_backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://ghosttrack:ghosttrack_dev_password@postgres:5432/ghosttrack
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - redis

  frontend:
    build: ./frontend
    container_name: ghosttrack_frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - backend

volumes:
  postgres_data:
